version: "3.8"
services:
  packer-utils:
    image: hashicorp/packer:1.7.8
    env_file: .env
    environment:
      - PACKER_PLUGIN_PATH=/workspace/.packer.d/plugins
    entrypoint: ""
    volumes:
      - .:/work
    working_dir: /work

  envvars:
    image: flemay/envvars:0.0.6
    env_file: .env
    working_dir: /work
    volumes:
      - .:/work
